### ISSUE TITLE
Waffle webhooks for rootio/rootio.github.io

### ISSUE THREAD

**Issue by mgax** [rootio/project#1]
My github account doesn't have admin permissions for https://github.com/rootio/rootio.github.io, therefore waffle can't add its webhooks to it.

**Comment by mgax** [comment]
@judelove can you please log into waffle? Maybe it can use your account to add the hooks.

**Comment by judelove** [comment]
Hello Alex, I did that and turned on hooks. Is that what you needed?

Regards,

jude

**Comment by mgax** [comment]
Waffle stopped complaining, so it must have worked. Thanks!
