### ISSUE TITLE
DigitalOcean account

### ISSUE THREAD

**Issue by mgax** [rootio/project#2]
Create a DigitalOcean account with a valid credit card.

**Comment by mgax** [comment]
For reference, here's a comparison of various European VPS providers, including network bandwidth: https://github.com/joedicastro/vps-comparison#speedtest

**Comment by Luthieneye** [comment]
any updates here?

**Comment by mgax** [comment]
@judelove did you manage to add a credit card to the account?

**Comment by judelove** [comment]
I dont know what happened before, but it looks like today Digital Ocean was ok with using my debit card. So, done

**Comment by mgax** [comment]
Can you please give me access to the account? Thanks.

**Comment by judelove** [comment]
@mgax have given you access. let me know if it is enough

**Comment by mgax** [comment]
> have given you access. let me know if it is enough

Yes, I was able to create a droplet. Thanks!
